Add main-service
stasyaofit/java-explore-with-me pull request #3
Opened 2023-09-25 11:43 UTC by stasyaofit

2023-09-27 12:38 UTC, afomkina requested changes
Отличная работа получилась, молодец 🔥

2023-09-27 12:38 UTC, afomkina commented on ewm-main-service/src/main/java/ru/practicum/dto/event/EventShortDto.java
> +public class EventShortDto extends EventDto{
Лучше использовать `EventDto`, так как этот объект никак его не расширяет

2023-09-27 12:38 UTC, AnastasiyaFomkina commented on ewm-main-service/src/main/java/ru/practicum/repository/CategoryRepository.java
> +    Optional<Category> findFirst1ByName(String name);
Кажется, данный метод нигде не используется

2023-09-27 12:38 UTC, AnastasiyaFomkina commented on ewm-main-service/src/main/java/ru/practicum/repository/CompilationRepository.java
> +    Page<Compilation> findAllByPinned(Boolean pinned, Pageable pageable);
Нужно возвращать список. Так как при `Pageable` запросе `SpringData` будет возвращать список с определенным количеством элементов. Объект `Page` нам не нужен, так как мы его никак не используем, кроме как кастуем обратно к списку

2023-09-27 12:38 UTC, AnastasiyaFomkina commented on ewm-main-service/src/main/java/ru/practicum/service/Impl/CompilationServiceImpl.java
> +    @Transactional(readOnly = true)
Лучше вынести данную аннотацию на уровень класса, а в нужных местах переопределить. Вот [отличная статья ](https://habr.com/ru/companies/otus/articles/649093/) на этот счет; 
Лучше проработать для всех сервисов

2023-09-27 12:38 UTC, AnastasiyaFomkina commented on ewm-main-service/src/main/java/ru/practicum/service/Impl/ParticipationRequestServiceImpl.java
> +    @Transactional(readOnly = true)
Нет смысла повторно ее добавлять, так как данная транзакция уже определена на уровне класса

2023-09-27 12:38 UTC, AnastasiyaFomkina commented on ewm-main-service/src/main/resources/schema.sql
Стоит добавить [индексы](https://tproger.ru/articles/indeksy-v-postgresql/), чтобы ускорить поиск

2023-09-27 19:13 UTC, stasyaofit commented on ewm-main-service/src/main/java/ru/practicum/dto/event/EventShortDto.java
> +public class EventShortDto extends EventDto{
Анастасия, здравствуйте. Поменял на EventDto, теперь возникает такая проблема. 
Ambiguous mapping methods found for mapping collection element to ru.practicum.dto.event.EventDto: ru.practicum.dto.event.EventFullDto ru.practicum.mapper.EventMapper.mapToEventFullDto(ru.practicum.model.Event event), ru.practicum.dto.event.EventDto ru.practicum.mapper.EventMapper.mapToEventDto бывший mapToEventShortDto  (ru.practicum.model.Event event). See https://mapstruct.org/faq/#ambiguous for more info.

Не могу понять в чем дело, объекты по содержанию одинаковы по сути. Сломался метод в котором поменял тип возвращаемого значения и тот. что вообще не трогал

2023-09-27 21:35 UTC, stasyaofit commented on ewm-main-service/src/main/java/ru/practicum/dto/event/EventShortDto.java
> +public class EventShortDto extends EventDto{
Решено.

2023-09-28 15:24 UTC, AnastasiyaFomkina approved these changes

2023-09-28 17:40 UTC, merged